### ISSUE TITLE
ChemRxiv Engage API integration

### ISSUE THREAD

**Issue by jannisborn** [PhosphorylatedRabbits/paperscraper#17]
Turns out, OpenEngage *does* provide an API :)

Base url: https://chemrxiv.org/engage/chemrxiv/public-api/v1/items

See code here: https://github.com/chemrxiv-dashboard/chemrxiv-dashboard.github.io/commit/d3816f6587efcda91bd0bb4c2e57c15a4d5dba13#diff-d34f2e1442f7c9783f9229f7808dd7cbd276b7229ddea80b65146e4bed283ef7

Will try to integrate this as soon as possible

**Comment by arifin-chemist89** [comment]
Good to know about it. Looking forward for the implementation!
