### ISSUE TITLE
No DOI given in saved dumps of recent arxiv papers

### ISSUE THREAD

**Issue by mwarqee** [PhosphorylatedRabbits/paperscraper#26]
Ran 

```
from paperscraper.arxiv import get_and_dump_arxiv_papers

prompt = ['prompt engineering llm', 'prompt injection llm']
ai = ['Artificial intelligence', 'Large Language Models', 'OpenAI','LLM']
mi = ['ChatGPT']
query = [prompt, ai, mi]

get_and_dump_arxiv_papers(query, output_filepath='pro_inject.jsonl')
```

Example - jsonl contains title,authors,abstract for the page  https://arxiv.org/abs/2302.11382 but journal is always blank and doi is null. This pattern repeats itself for all results.

**Comment by jannisborn** [comment]
Hi @mwarqee,

Thanks for the interest in this tool and reporting this issue. 
I really dont know what you expect from the tool in this case. Arxiv is a preprint server. How should the journal be set to anything. By definition those are preprints and not peer-reviewed. Furthermore, arxiv does not assign DOIs so how should there be any?

**Comment by mwarqee** [comment]
Apologies for not providing more detail, perhaps I misunderstood the purpose of the module.
[This section](https://github.com/PhosphorylatedRabbits/paperscraper#scrape-pdfs) refers to the option of downloading PDFs  based on the jsonl file
```
from paperscraper.pdf import save_pdf_from_dump

# Save PDFs in current folder and name the files by their DOI
save_pdf_from_dump('medrxiv_covid_ai_imaging.jsonl', pdf_path='.', key_to_save='doi')
```
Since the dump does not cotain any DOI then no files will be downloaded. Furthermore if I check the arxiv site for one paper there is an arXiv doi
https://doi.org/10.48550/arXiv.2302.11382 and coresponding link for the paper - https://arxiv.org/pdf/2302.11382

So I am bit puzzled, or maybe misunderstanding how the paper download should work for arXiv?

**Comment by jannisborn** [comment]
Fair point but this is a completely different thing from what you described in your first post. Arxiv introduced DOIs in 2022 (see https://blog.arxiv.org/2022/02/17/new-arxiv-articles-are-now-automatically-assigned-dois/), so while the vast majority of the arxiv DB will still not have DOIs a small fraction of recent papers will have DOIs. For those papers, it would be great if the DOI would be added to the `jsonl` dump, on this I completely agree, thanks for pointing this out

**Comment by jannisborn** [comment]
HI @mwarqee, please check the PR I opened (#27)
