### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by donnate** [PhosphorylatedRabbits/paperscraper#4]
Hi!

Sorry to take up your time with this, but I have a small issue when trying to use the package on chemrxiv/biorxiv and medrxiv.
The import fails, and I have a no module found error (I have attached a snapshot).
![Screenshot 2021-03-03 at 3 48 51 PM](https://user-images.githubusercontent.com/7548710/109888235-017e4f80-7c38-11eb-8cf3-5ccbb3fd02e5.png)

I was wondering if I had missed something?

Thank you very much for making this package open source, I look forward to using it!
Best regards,

Claire

**Comment by drugilsberg** [comment]
Hi @donnate thanks a reporting this, I think I understood where the issues is (a missing `__init__.py` most likely).
Will keep you posted and let you know once we have a fix ready.

**Comment by drugilsberg** [comment]
This should be addressed once this PR is merged: https://github.com/PhosphorylatedRabbits/paperscraper/pull/5.
Afterwards, the version 0.0.2 that will be available from PYPI via pip should not cause the import issue.

**Comment by drugilsberg** [comment]
HI @donnate the fix has been released and the new version is available on PYPI: https://pypi.org/project/paperscraper/.
Please try again updating the package version:
```console
pip install paperscraper==0.0.2
```
In case the import error is solved, please close the issue.

**Comment by donnate** [comment]
Hi,

thanks a lot!
There seems to be a small typo in one of your init files:

<img width="1369" alt="Screenshot 2021-03-04 at 8 28 26 AM" src="https://user-images.githubusercontent.com/7548710/109996040-b14ccf00-7cc3-11eb-8e7a-cff6327b2108.png">

Best ,

Claire

**Comment by donnate** [comment]
Hi,
Thanks I think it works!
Will keep you posted if I see anything else, but thanks again for the package, this looks great!
